question = Question.create(content: "Which of the following is a backend language?")
question.answers.create(content: "Ruby", is_correct: true)
question.answers.create(content: "Javascript", is_correct: false)
question.answers.create(content: "SASS", is_correct: false)
question.answers.create(content: "hashstachetocat", is_correct: false)

question = Question.create(content: "Which of the following is a database language?")
question.answers.create(content: "SQL", is_correct: true)
question.answers.create(content: "Git", is_correct: false)
question.answers.create(content: "Python", is_correct: false)
question.answers.create(content: "hashstachetocat", is_correct: false)

question = Question.create(content: "How awesome is Baylee?")
question.answers.create(content: "Mostly awesome", is_correct: false)
question.answers.create(content: "Very awesome", is_correct: false)
question.answers.create(content: "Gatsby-awesome", is_correct: true)
question.answers.create(content: "hashstachetocat", is_correct: false)

question = Question.create(content: "What does SEO stand for?")
question.answers.create(content: "Search Engine Optimization", is_correct: true)
question.answers.create(content: "Standard Encryption Ontology", is_correct: false)
question.answers.create(content: "Sexy Expressive Output", is_correct: false)
question.answers.create(content: "hashstachetocat", is_correct: false)

question = Question.create(content: "Which of the following indicates a hash in Ruby?")
question.answers.create(content: "<>", is_correct: false)
question.answers.create(content: "()", is_correct: false)
question.answers.create(content: "[]", is_correct: false)
question.answers.create(content: "{:creepy => 'hashstachetocat'}", is_correct: true)

question = Question.create(content: "Which of the following is a frontend framework?")
question.answers.create(content: "Bootstrap", is_correct: true)
question.answers.create(content: "Yet Another Markup Language", is_correct: false)
question.answers.create(content: "HAML", is_correct: false)
question.answers.create(content: "hashstachetocat", is_correct: false)

question = Question.create(content: "What are Franky's favorite subjects?")
question.answers.create(content: "Security and optimization", is_correct: true)
question.answers.create(content: "Design", is_correct: false)
question.answers.create(content: "TDD", is_correct: false)
question.answers.create(content: "hashstachetocat", is_correct: false)

question = Question.create(content: "Who is best known for saying 'Is it mobile-friendly?'")
question.answers.create(content: "Adam 'darkside' Daigian", is_correct: true)
question.answers.create(content: "Franky 'the wall' Wahl", is_correct: false)
question.answers.create(content: "Zara 'not Sarah' Peisker", is_correct: false)
question.answers.create(content: "hashstachetocat", is_correct: false)

question = Question.create(content: "Which publication does not cover tech?")
question.answers.create(content: "Vogue", is_correct: true)
question.answers.create(content: "Betabeat", is_correct: false)
question.answers.create(content: "Techcrunch", is_correct: false)
question.answers.create(content: "The hashstachetocat Record", is_correct: false)

question = Question.create(content: "If @monkey has many bananas, what is the SQL call to get bananas?")
question.answers.create(content: "@monkey.bananas", is_correct: true)
question.answers.create(content: "bananas", is_correct: false)
question.answers.create(content: "bananas.@monkey", is_correct: false)
question.answers.create(content: "@hashstachetocat.bananas", is_correct: false)

question = Question.create(content: "Who are the members of the best four-person team in the world?")
question.answers.create(content: "Zara, Patsy, Christina, Baylee", is_correct: true)
question.answers.create(content: "John, Paul, George, Ringo", is_correct: false)
question.answers.create(content: "Charlotte, Carrie, Miranda, Samantha", is_correct: false)
question.answers.create(content: "hashstachetocat, hashstachetokitty, hashstachetotiger, hashstachetolion", is_correct: false)

question = Question.create(content: "What is the best default programming word?")
question.answers.create(content: "poop", is_correct: true)
question.answers.create(content: "foo", is_correct: false)
question.answers.create(content: "bar", is_correct: false)
question.answers.create(content: "hashstachetocat", is_correct: false)

question = Question.create(content: "How much fun are you having right now?")
question.answers.create(content: "fun", is_correct: false)
question.answers.create(content: "fun fun", is_correct: false)
question.answers.create(content: "fun fun fun", is_correct: false)
question.answers.create(content: "fun fun fun fun", is_correct: true)